services:
  nginx-ds:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8850:80"
    depends_on:
        - php-ds
    container_name: nginx-ds
  php-ds:
      build:
        context: .
        dockerfile: _docker/app/Dockerfile
      volumes:
        - ./:/var/www/
      depends_on:
          - db-ds
      container_name: php-ds
  db-ds:
      image: postgres:14
      restart: always
      volumes:
        - ./_docker/postgres/datadir:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      container_name: db-ds
  node-ds:
      build:
          context: .
          dockerfile: ./_docker/nodejs/Dockerfile
      tty: true
      ports:
          - "5173:5173"
      working_dir: /var/www
      volumes:
          - .:/var/www # Монтируем локальную папку в контейнер как /var/www
      container_name: node-ds
