openapi: 3.0.1
info:
  title: DS
  description: 'DS api'
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:8000/api'
    description: 'Local API server'
tags:
  - name: Authenticate
  - name: Collectors
paths:
  /authenticate:
    $ref: './partials/paths/authenticate.yaml'
  /register:
    $ref: './partials/paths/register.yaml'
  /collectors:
    $ref: './partials/paths/collectors.yaml'
  /collector/{slug}:
    $ref: './partials/paths/collector.yaml'
components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
